import Categories.Category.Monoidal.BiClosed
import IL
import IL.Core
import IL.Dual
import IL.Monoidal
import IL.Properties
import MCIL
import MCIL.Core
import MCIL.Properties
import NatEquiv
import Prelude
import concrete-examples
import fil
import fil-examples
import playground
